[config]

[config.wallpaper]
set = false
command = "true"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt-colors]
input_path = '~/.config/matugen/templates/qt-colors.conf'
output_path = '~/.local/share/color-schemes/matugen.colors'

[templates.swaylock]
input_path = '~/.config/matugen/templates/swaylock-config'
output_path = '~/.config/swaylock/config'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.regreet]
input_path = '~/.config/matugen/templates/regreet.css'
output_path = '~/.config/matugen/generated/regreet.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors-rofi.rasi'
output_path = '~/.config/rofi/colors/matugen.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.config/waybar/colors-matugen.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors-swaync.css'
output_path = '~/.config/swaync/colors-matugen.css'
