bg="#1A1B26"
default_fg="#C0CAF5"
session_fg="#9ECE6A"
session_selection_fg="#1A1B26"
session_selection_bg="#414868"
active_window_fg="#BB9AF7"
active_pane_border="#414868"

set -g status-right "#[fg=${session_fg}]#(whoami)@#h#[fg=${default_fg}] | #{cpu_percentage} | %a %h-%d %H:%M"
set -g status-justify centre
set -g status-right-length 200 # default: 10
set -g status-left-length 200  # default: 10
set -g status-style "bg=${bg}"
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]   #S"
set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W"
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"
