[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/dotfiles/env/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "cat --color=always ~/dotfiles/env/.config/tmux/tmux.conf"

